redirect_to_lowercase:
    path: /{url}/
    defaults: { _controller: StefaniusLowerCaseRedirectorBundle:Redirect:lowerCase }
    requirements:
        url: "^[A-Z]+[A-Za-z0-9]+|[A-Z]+[A-Za-z0-9]+|[A-Za-z0-9]+[A-Z]+|[A-Za-z0-9]+[A-Z]+[A-Za-z0-9]+$"
    methods: [GET]